import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-orcamentopesquisa',
  templateUrl: './orcamentopesquisa.component.html',
  styleUrls: ['./orcamentopesquisa.component.css']
})
export class OrcamentopesquisaComponent {
  orcamento = [
    { dataCadastro: '25/10/2019', dataLancamto: '25/10/2019', horaLancamto: '0:00 ',
    clinica: 'MEIER ', tipo: 'CONTRATADO	', ficha: '5930 ',
    paciente: 'GISLANE SANTOS DE SANTANA	     ', indicacao: 'CLINICA',
    numFichaIndicante: '77777', nomeIndicante:  'MONICA',
    dentista:  'FELIPE COLLYER', especialidade: 'CGERAL'},
    { dataCadastro: '08/09/2014',dataLancamto: '29/08/2019', horaLancamto: '10:31',
    clinica: 'CAXIAS', tipo: 'CONTRATADO	', ficha: '10849',
    paciente: 'RAISSA SANTOS GENUINO	         ', indicacao: 'CLINICA',
    numFichaIndicante: '77777', nomeIndicante:  'MONICA', dentista:  'VINICIUS',
    especialidade: 'CGERAL'},
    { dataCadastro: '25/10/2019', dataLancamto:'25/10/2019', horaLancamto: '0:00 ',
    clinica: 'MEIER ', tipo: 'CONTRATADO	', ficha: '14121',
    paciente: 'PAULA FORTUNATO', indicacao: 'CLINICA',
    numFichaIndicante: '77777', nomeIndicante:  'MONICA', dentista:  'FELIPE COLLYER',
    especialidade: 'CGERAL'},
    { dataCadastro: '24/10/2019', dataLancamto: '25/10/2019', horaLancamto: '0:00 ',
    clinica: 'MEIER ',tipo: 'CONTRATADO	', ficha: '14878',
    paciente: 'NILZA ROSA DE OLIVEIRA DOS SANTOS', indicacao: 'CLINICA',
    numFichaIndicante: '77777', nomeIndicante:  'MONICA', dentista:  'FELIPE COLLYER',
    especialidade: 'CGERAL'},
    { dataCadastro: '27/10/2017', dataLancamto: '21/08/2019', horaLancamto: '14:26',
    clinica: 'CAXIAS',tipo: 'ORCTO	        ', ficha: '19303',
    paciente: 'ROSILENE CRISTINA S FREITAS	     ', indicacao: 'PORTA  ',
    numFichaIndicante: '77777',nomeIndicante:  'MONICA', dentista:  'ADRIANA',
    especialidade: 'CGERAL'},
    { dataCadastro: '28/03/2018',dataLancamto: '21/08/2019', horaLancamto: '15:44',
    clinica: 'CAXIAS',tipo: 'ORCTO	        ', ficha: '20278',
    paciente: 'RAIMUNDA ALVES FERREIRA	         ', indicacao: 'PORTA  ',
    numFichaIndicante: '4444 ',nomeIndicante:  'MONICA', dentista:  'ADRIANA',
    especialidade: 'CGERAL'},
    { dataCadastro: '20/08/2019', dataLancamto: '20/08/2019', horaLancamto: '18:13',
    clinica: 'CAXIAS',tipo: 'ORCTO	        ', ficha: '23021',
    paciente: 'SABRINA DAMASIO	                 ', indicacao: 'PORTA  ',
    numFichaIndicante: '77777', nomeIndicante:  'ELIANE', dentista:  'VINICIUS',
    especialidade: 'CGERAL'},
    { dataCadastro: '21/08/2019',dataLancamto: '21/08/2019', horaLancamto: '9:30 ',
    clinica: 'CAXIAS',tipo: 'ORCTO	        ', ficha: '23023',
    paciente: 'JAKSON FERREIRA DA SILVA	     ', indicacao: 'PORTA  ',
    numFichaIndicante: '77777', nomeIndicante:  'MONICA', dentista:  'RAFAEL',
    especialidade: 'CGERAL'},
    { dataCadastro: '21/08/2019', dataLancamto: '21/08/2019', horaLancamto: '11:05',
    clinica: 'CAXIAS',tipo: 'ORCTO	        ', ficha: '23026',
    paciente: 'LUCIENE GERMANO SILVA FERREIRA	 ', indicacao: 'PORTA  ',
    numFichaIndicante: '77777', nomeIndicante:  'ELIANE', dentista:  'RAFAEL',
    especialidade: 'C GERAL'},
    { dataCadastro: '21/08/2019', dataLancamto: '21/08/2019',horaLancamto: '14:00',
    clinica: 'CAXIAS',tipo: 'ORCTO	        ', ficha: '23028',
    paciente: 'MICAELI ALICE CARVALHO	         ', indicacao: 'CLINICA',
    numFichaIndicante: '77777', nomeIndicante:  'MONICA', dentista:  'BIANCA',
    especialidade: 'CGERAL'}
    ];

    dente = [
      { label: 'Sem', value: '00'},
      { label: '18', value: '18'},
      { label: '17', value: '17'},
      { label: '16', value: '16'},
      { label: '15', value: '15'},
      { label: '14', value: '14'},
      { label: '13', value: '13'},
      { label: '12', value: '12'},
      { label: '11', value: '11'},
      { label: '21', value: '21'},
      { label: '22', value: '22'},
      { label: '23', value: '23'},
      { label: '24', value: '24'},
      { label: '25', value: '25'},
      { label: '26', value: '26'},
      { label: '27', value: '27'},
      { label: '28', value: '28'},
      { label: '48', value: '48'},
      { label: '47', value: '47'},
      { label: '46', value: '46'},
      { label: '45', value: '45'},
      { label: '44', value: '44'},
      { label: '43', value: '43'},
      { label: '42', value: '42'},
      { label: '41', value: '41'},
      { label: '31', value: '31'},
      { label: '32', value: '32'},
      { label: '33', value: '33'},
      { label: '34', value: '34'},
      { label: '35', value: '35'},
      { label: '36', value: '36'},
      { label: '37', value: '37'},
      { label: '38', value: '38'},

    ];
    face = [
      { label: 'Sem', value: '0'},
      { label: '1-C', value: '1'},
      { label: '2-D', value: '2'},
      { label: '3-S', value: '3'},
      { label: '4-E', value: '4'},
      { label: '5-I', value: '5'},
    ];


  servicos1 = [
    { label: 'Extração', value: '101'},
    { label: 'Provisório', value: '102'},
    { label: 'Obt. Resina', value: '103'},
    { label: 'Remoção de Tartaro', value: '104'},
    { label: 'Polimento', value: '105'},
    { label: 'Fluor', value: '106'},
    { label: 'Selante', value: '107'},
    { label: 'Clareamento Clínico', value: '108'},
    { label: 'Clareamento Caseiro', value: '109'},
    { label: 'Clareamento Combinado', value: '110'},
    { label: 'Bloco Cerômero', value: '111'},
    { label: 'Bloco Metal', value: '112'},
    { label: 'Bloco Resina', value: '113'},
    { label: 'Bloco Metalo', value: '114'},
    { label: 'Bloco Ceramica', value: '115'},
    { label: 'Radiografia', value: '116'},
    { label: 'Raspagem Supra Gengival Sup.', value: '117'},
    { label: 'Raspagem Supra Gengival Inf.', value: '118'},
  ];

  servicos2 = [
    { label: 'Roach Superior', value: '201'},
    { label: 'Roach Inferior', value: '202'},
    { label: 'Dentadura Rosa Superior', value: '203'},
    { label: 'Dentadura Rosa Inferior', value: '204'},
    { label: 'Dentadura Incolor Superior', value: '205'},
    { label: 'Dentadura Incolor Inferior', value: '206'},
    { label: 'Conserto Prótese', value: '207'},
    { label: 'Flex Superior', value: '208'},
    { label: 'Flex Inferior', value: '209'},
    { label: 'Pivot', value: '210'},
    { label: 'TTO Canal Anterior', value: '211'},
    { label: 'TTO Canal Pré Molar', value: '212'},
    { label: 'TTO Canal Molar', value: '213'},
    { label: 'Núcleo Metálico', value: '214'},
    { label: 'Núcleo Fibra Vidro', value: '215'},
    { label: 'Adesiva', value: '216'},
    { label: 'Limpeza Completa', value: '217'},

  ];
}
